### ISSUE TITLE
I'm getting an error with Admob integration.

### ISSUE THREAD

**Issue by satoshi512** [insthync/unity-simple-monetization-admob#1]
I am using "Bomber io PUN".

I set it as described in "Admob integration", but before setting the app ID, an error like the one in the attachment appears and integration is not possible. 

Do you have any countermeasures?
![2021 11 22](https://user-images.githubusercontent.com/86067972/142770733-6ad5b256-e347-4865-8231-8d9c9f0d347d.png)

**Comment by insthync** [comment]
Load latest plugin update.
